name: "NextPVR"
guid: "9574ac10-bf23-49bc-949f-924f23cfa48f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-nextpvr.png"
version: 10
targetAbi: "10.9.2.0"
framework: "net8.0"
overview: "Live TV plugin for NextPVR"
description: >
  Provides access to live TV, program guide, and recordings from NextPVR.

category: "LiveTV"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.NextPVR.dll"
changelog: |-
  - Allow dynamic recording URLs (#49) @emveepee
