---
name: "NextPVR"
guid: "9574ac10-bf23-49bc-949f-924f23cfa48f"
version: "3.0.0.0"
targetAbi: "10.5.0.0"
overview: "Live TV plugin for NextPVR"
description: >
  Provides access to live TV, program guide, and recordings from NextPVR.
category: "LiveTV"
owner: "jellyfin"
artifacts:
- "NextPvr.dll"
changelog: >
  changelog
