---
name: "jellyfin-plugin-nextpvr"
guid: "9574ac10-bf23-49bc-949f-924f23cfa48f"
version: "3"
jellyfin_version: "10.5.0"
nicename: "NextPVR"
description: "Live TV plugin for NextPVR"
overview: >
  Provides access to live TV, program guide, and recordings from NextPVR.
category: "LiveTV"
owner: "jellyfin"
artifacts:
  - "NextPvr.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
