name: "NextPVR"
guid: "9574ac10-bf23-49bc-949f-924f23cfa48f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-nextpvr.png"
version: 13
targetAbi: "10.11.1.0"
framework: "net9.0"
overview: "Live TV plugin for NextPVR"
description: >
  Provides access to live TV, program guide, and recordings from NextPVR.

category: "LiveTV"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.NextPVR.dll"
changelog: |-
  - UTC fixes (#70) @emveepee
  - Use 7.0.3 deferred art (#71) @emveepee
